routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

$url_parameters = @explode(".", $_SERVER['HTTP_HOST']);

Route::domain(env('APP_ENV') == 'production' ? 'lithiumatc.xyz' : env('APP_DOMAIN', 'localhost'))->group(function() {
    Route::get('/', 'HomeController@home')->name('home');
    Route::get('/pricing', 'HomeController@pricing')->name('pricing');
    Route::get('/community', 'HomeController@commRedir')->name('communityredir');
    Route::get('/sessionforward', 'AuthController@forward')->name('login.forward');
    Route::middleware(['auth', 'sysadmin'])->prefix('/admin')->name('admin.')->group(function() {
        Route::get('/', 'Admin\MainController@home')->name('index');
        Route::get('/commRedir', function() {
            return redirect()->route('admin.communities.index');
        })->name('communitie');
        Route::resource('/communities', 'Admin\CommunitiesController');
        Route::get('/settings', 'Admin\MainController@settings')->name('settings');

        Route::post('/settings/banner/activate', 'Admin\MainController@activateBanner')->name('settings.banner.activate');
        Route::post('/settings/banner/deactivate', 'Admin\MainController@deactivateBanner')->name('settings.banner.deactivate');
        Route::post('/settings/banner', 'Admin\MainController@saveBanner')->name('settings.banner.save');
    });
    Route::middleware('auth')->get('/discord/link', 'Communities\Admin\DiscordSyncController@link')->name('discord.link');
});


Route::get('/login', 'AuthController@login')->middleware('guest')->name('login');
Route::get('/login/cb', 'AuthController@loginCb')->name('login.cb');
Route::post('/logout', 'AuthController@logout')->name('logout');

Route::domain('{community}.' . env('APP_DOMAIN'))->middleware(['community'])->group(function() {
    Route::middleware('auths')->name('c.')->group(function() {
        Route::get('/', 'Communities\HomeController@home')->name('home');
        Route::middleware('concurrent')->group(function() {
            Route::middleware('perm:pilot')->prefix('/pilot')->group(function() {
                Route::get('/', 'Communities\PilotController@pilotdash')->name('pilotdash');
                Route::get('/file', 'Communities\PilotController@fileplan')->name('fileplan');
                Route::post('/file', 'Communities\PilotController@processFile')->name('fileplan.process');
                Route::get('/file/review/{plan}', 'Communities\PilotController@reviewPlan')->name('fileplan.review');
                Route::post('/file/review/{plan}/edit', 'Communities\PilotController@cancelReview')->name('fileplan.review.reject');
                Route::post('/file/review/{plan}/file', 'Communities\PilotController@file')->name('fileplan.review.approve');
                Route::post('/cancel', 'Communities\PilotController@cancelCurrent')->name('pilotdash.cancel');

                Route::get('/charts', 'Communities\PilotController@getCharts')->name('pilot.charts');
            });
            Route::middleware(['perm:atc', 'feature:atc'])->prefix('/atc')->group(function() {
                Route::get('/', 'Communities\ATCController@atcdash')->name('atc.index');
                Route::get('/strips', 'Communities\ATCController@flightstrips')->middleware('feature:flight-strips')->name('atc.strips');
                Route::get('/active', 'Communities\ATCController@active')->name('atc.active');
                Route::get('/frequency', 'Communities\ATCController@changeFreq')->name('atc.frequency');
                Route::post('/frequency', 'Communities\ATCController@processFreqChange')->name('atc.frequency.process');
            });
            Route::middleware('perm:admin')->prefix('/admin')->name('admin.')->group(function() {
                Route::get('/', 'Communities\Admin\MainController@overview')->name('index');
                Route::post('/', 'Communities\Admin\MainController@saveOverview')->name('o.save');
                Route::resource('/airlines', 'Communities\Admin\AirlineController');
                Route::get('/airlines/{airline}/webhook', 'Communities\Admin\AirlineController@newHook')->name('airlines.newhook');
                Route::post('/airlines/{airline}/webhook', 'Communities\Admin\AirlineController@addHook')->name('airlines.webhook');
                Route::delete('/airlines/{airline}/webhook/{hook}', 'Communities\Admin\AirlineController@delHook')->name('airlines.delhook');
                Route::resource('/discord', 'Communities\Admin\DiscordSyncController');
                Route::get('/discordlink', 'Communities\Admin\DiscordSyncController@startLink')->name('discord.link');
                Route::delete('/discordlink', 'Communities\Admin\DiscordSyncController@unlink')->name('discord.unlink');
                Route::resource('/airports', 'Communities\Admin\AirportsController');
                Route::get('/airports/{airport}/charts/new', 'Communities\Admin\AirportsController@newChart')->name('airports.charts.create');
                Route::post('/airports/{airport}/charts', 'Communities\Admin\AirportsController@storeChart')->name('airports.charts.store');
                Route::get('/airports/{airport}/charts/{chart}/edit', 'Communities\Admin\AirportsController@editChart')->name('airports.charts.edit');
                Route::patch('/airports/{airport}/charts/{chart}', 'Communities\Admin\AirportsController@updateChart')->name('airports.charts.update');
                Route::delete('/airports/{airport}/charts/{chart}', 'Communities\Admin\AirportsController@deleteChart')->name('airports.charts.delete');

                Route::get('/settings', 'Communities\Admin\MainController@settings')->middleware('feature:customize')->name('settings');
                Route::post('/settings', 'Communities\Admin\MainController@saveSettings')->middleware('feature:customize')->name('settings.save');
            });
        });

    });
    Route::get('/suspended', 'Communities\HomeController@suspended')->name('suspended');
    Route::get('/userlimit', 'Communities\HomeController@userlimit')->name('userlimit');
    Route::get('/sessionforward', 'AuthController@forwardPrc')->middleware('guest')->name('login.forwardprc');
    //\Illuminate\Support\Facades\Broadcast::routes();
});

app/Community.php
<?php

namespace App;

use App\Plans\DemoPlan;
use App\Plans\ExtremePlan;
use App\Plans\StandardPlan;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;

class Community extends Model
{
    public const PLAN_STANDARD = 0;
    public const PLAN_EXTREME = 1;
    public const PLAN_DEMO = 2;

    public const AVAILABLE_SETTINGS = [
        'Look & Feel' => [
            'branding' => [
                'name' => 'Brand URL',
                'type' => 'text',
                'validators' => 'nullable|string|url|max:255',
                'is_color' => false,
                'is_background' => false
            ],
            'backgrounds-home' => [
                'name' => 'Homepage Background',
                'type' => 'text',
                'validators' => 'nullable|string|max:50',
                'is_color' => true,
                'is_background' => true
            ],
            'backgrounds-pilot' => [
                'name' => 'Pilot Background',
                'type' => 'text',
                'validators' => 'nullable|string|max:50',
                'is_color' => true,
                'is_background' => true
            ],
            'backgrounds-atc' => [
                'name' => 'ATC Background',
                'type' => 'text',
                'validators' => 'nullable|string|max:50',
                'is_color' => true,
                'is_background' => true
            ],
            'backgrounds-admin' => [
                'name' => 'Admin Background',
                'type' => 'text',
                'validators' => 'nullable|string|max:50',
                'is_color' => true,
                'is_background' => true
            ],
//            'backgrounds-nav' => [
//                'name' => 'Navbar Background',
//                'type' => 'text',
//                'validators' => 'nullable|string|max:50',
//                'is_color' => true,
//                'is_background' => true
//            ],
//            'foregrounds-nav' => [
//                'name' => 'Navbar Text Color',
//                'type' => 'text',
//                'validators' => 'nullable|string|max:50',
//                'is_color' => true,
//                'is_background' => false
//            ]
        ]
    ];

    protected $fillable = ['owner_id', 'name', 'plan_id', 'subdomain', 'enabled'];

    public function owner() {
        return $this->belongsTo('\App\User', 'owner_id');
    }

    public function getPlan() {
        switch($this->plan_id) {
            case self::PLAN_STANDARD:
                return new StandardPlan();
            case self::PLAN_EXTREME:
                return new ExtremePlan();
            case self::PLAN_DEMO:
                return new DemoPlan();
            default:
                return null;
        }
    }

    public function putSetting($setting, $value) {
        $s = Setting::where('setting', $setting)->where('community_id', $this->id)->first();
        if($s == null && $value == null) return;
        if($value == null) {
            $s->delete();
            return;
        }
        if($s == null) {
            $s = new Setting();
            $s->community_id = $this->id;
            $s->setting = $setting;
        }
        $s->value = $value;
        $s->save();

    }

    public function getSetting($setting, $default = null) {
        $s = Setting::where('setting', $setting)->where('community_id', $this->id)->first();
        if($s == null) return $default;
        return $s->value;
    }

    public function flights() {
        return $this->hasMany('App\Flight');
    }

    public function virtualAirlines() {
        return $this->hasMany('App\VirtualAirline');
    }

    public function controllerPresence() {
        return $this->hasMany('App\Presence', 'community_id');
    }

    public function discordSync() {
        return $this->hasMany('App\DiscordSync');
    }

    public function permissions() {
        return $this->hasMany('App\Permission');
    }

    public function scratchpad() {
        return $this->hasOne('App\Scratchpad');
    }

    public function messages() {
        return $this->hasMany('App\Message');
    }

    public function airports() {
        return $this->hasMany('App\Airport');
    }

    public function webhooks() {
        return $this->hasMany('App\Webhook');
    }

    public function isExceedingConcurrent() {
        $plan = $this->getPlan();
        if($plan->getMaxConcurrent() == -1) return false;
        $current = Activity::where('community_id', $this->id)->where('updated_at', '>', Carbon::now()->subMinutes(5))->count();
        $presence = Presence::where('community_id', $this->id)->count();
        $total = $current + $presence;
        if($total < $plan->getMaxConcurrent())
            return false;
        if(!Auth::check()) true;
        $included = Activity::where('community_id', community()->id)->where('user_id', Auth::user()->id)->where('updated_at', '>', Carbon::now()->subMinutes(5))->first();
        if($included != null) return false;
        else return true;
    }

    public function getOnlineUsers() {
        $current = Activity::where('community_id', $this->id)->where('updated_at', '>', Carbon::now()->subMinutes(5))->count();
        $presence = Presence::where('community_id', $this->id)->count();
        return $current+$presence;
    }

    public function getCustomizationAttribute() {
        return [
            'backgrounds-home' => $this->getSetting('backgrounds-home', 'gradient:home'),
            'backgrounds-pilot' => $this->getSetting('backgrounds-pilot', 'gradient:community'),
            'backgrounds-atc' => $this->getSetting('backgrounds-atc', 'gradient:community'),
            'backgrounds-admin' => $this->getSetting('backgrounds-admin', 'gradient:community'),
            'backgrounds-nav' => $this->getSetting('backgrounds-nav', 'color:363636'),
            'foregrounds-nav' => $this->getSetting('foregrounds-nav', 'color:ffffff'),
            'branding' => $this->getSetting('branding', asset('/img/conc2-light.png'))
        ];
    }

    public static function resolveColor($color, $bg = false) {
        $match = preg_match("/[a-zA-Z]{1,20}:[a-zA-Z0-9]{1,20}/", $color);
        if($match === false) return null;
        $spl = explode(":", $color);
        //return $spl;
        $type = $spl[0];
        $val = $spl[1];
        switch($type) {
            case 'gradient':
                if(!$bg) return null;
                if($val == "home") return "background: linear-gradient(235deg, #BABC4A 0%, #000000 100%), linear-gradient(235deg, #0026AC 0%, #282534 100%), linear-gradient(235deg, #00FFD1 0%, #000000 100%), radial-gradient(120% 185% at 25% -25%, #EEEEEE 0%, #EEEEEE 40%, #7971EA calc(40% + 1px), #7971EA 50%, #393E46 calc(50% + 1px), #393E46 70%, #222831 calc(70% + 1px), #222831 100%), radial-gradient(70% 140% at 90% 10%, #F5F5C6 0%, #F5F5C6 30%, #7DA87B calc(30% + 1px), #7DA87B 60%, #326765 calc(60% + 1px), #326765 80%, #27253D calc(80% + 1px), #27253D 100%);background-blend-mode: overlay, lighten, overlay, color-burn, normal;";
                if($val == "community") return "background: radial-gradient(ellipse farthest-side at 76% 77%, rgba(245, 228, 212, 0.25) 4%, rgba(255, 255, 255, 0) calc(4% + 1px)), radial-gradient(circle at 76% 40%, #fef6ec 4%, rgba(255, 255, 255, 0) 4.18%), linear-gradient(135deg, #ff0000 0%, #000036 100%), radial-gradient(ellipse at 28% 0%, #ffcfac 0%, rgba(98, 149, 144, 0.5) 100%), linear-gradient(180deg, #cd6e8a 0%, #f5eab0 69%, #d6c8a2 70%, #a2758d 100%);background-blend-mode: normal, normal, screen, overlay, normal;";
                break;
            case 'color':
                return ($bg ? 'background-color: ' : '') . "#" . $val . ($bg ? ' !important;' : '');
            default:
                return null;
        }
        return null;
    }
}

resources/views/templates/admin.blade.php
@extends('templates.public')


@section('header')
    <style>
        html{
            height: 100%;
        }
        body{
            background: linear-gradient(125deg, #ECFCFF 0%, #ECFCFF 40%, #B2FCFF calc(40% + 1px), #B2FCFF 60%, #5EDFFF calc(60% + 1px), #5EDFFF 72%, #3E64FF calc(72% + 1px), #3E64FF 100%);
            height: 100%;
        }
    </style>
@endsection

@section('pub_body')
    <div class="container mt-3 mb-3 slide-in-fwd-center">
        <div class="columns">
            <div class="column is-one-fifth">
                <aside class="menu">
                    <p class="menu-label">Administration Portal</p>
                    <ul class="menu-list">
                        <li><a href="{{ route('admin.index') }}" class="{{ active('admin.index') }}">Overview</a></li>
                        <li><a href="{{ route('admin.communitie') }}" class="{{ active('admin.communitie') }}">Communities</a></li>
                        <li><a href="{{ route('admin.settings') }}" class="{{ active('admin.settings') }}">System Settings</a></li>
                    </ul>
                </aside>
            </div>
            <div class="column">
                @yield('admin_body')
            </div>
        </div>
    </div>
@endsection

resources/views/templates/app.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{{ isset($title) ? $title : "LithiumATC"}}</title>
    <link rel="stylesheet" href="{{ asset('/css/app.css') }}" />
    <link rel="shortcut icon" type="image/png" href="{{ asset('img/conc2.png') }}">
    @yield('header')
</head>
<body>
    @yield('body')

    <script src="{{ asset('/js/app.js') }}"></script>
    @yield('footer')
</body>
</html>

resources/views/templates/community.blade.php
@extends('templates.app')
<style>
.slide-in-fwd-center{-webkit-animation:slide-in-fwd-center .4s cubic-bezier(.25,.46,.45,.94) both;animation:slide-in-fwd-center .4s cubic-bezier(.25,.46,.45,.94) both}
/* ----------------------------------------------
 * Generated by Animista on 2020-4-14 19:8:5
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

@-webkit-keyframes slide-in-fwd-center{0%{-webkit-transform:translateZ(-1400px);transform:translateZ(-1400px);opacity:0}100%{-webkit-transform:translateZ(0);transform:translateZ(0);opacity:1}}@keyframes slide-in-fwd-center{0%{-webkit-transform:translateZ(-1400px);transform:translateZ(-1400px);opacity:0}100%{-webkit-transform:translateZ(0);transform:translateZ(0);opacity:1}}
/*    .navbar {
        {{ \App\Community::resolveColor(community()->customization['backgrounds-nav'], true) }}
        color: {{ \App\Community::resolveColor(community()->customization['foregrounds-nav']) }};
    }
    .navbar-item {
        color: {{ \App\Community::resolveColor(community()->customization['foregrounds-nav']) }} !important;
    }*/
</style>
@section('body')
    <nav class="navbar is-dark" role="navigation" aria-label="main navigation">
        <div class="navbar-brand">
            <a class="navbar-item" href="{{ coute('c.home') }}">
                <img src="{{ community()->customization['branding'] }}" height="100%" alt="LithiumATC" />
            </a>

            <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbar">
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
            </a>
        </div>

        <div id="navbar" class="navbar-menu">
            <div class="navbar-start">
                <a href="{{ coute('c.home') }}" class="navbar-item">
                    Home
                </a>
                @auth
                @perm('pilot')
                <a href="{{ coute('c.pilotdash') }}" class="navbar-item">
                    Pilot Dashboard
                </a>
                @endperm
                @perm('atc')
                <a href="{{ coute('c.atc.index') }}" class="navbar-item">
                    ATC Dashboard
                </a>
                @endperm
                @else

                @endauth
            </div>

            <div class="navbar-end">
            @perm('admin')
                <a href="{{ coute('c.admin.index') }}" class="navbar-item">
                Admin Dashboard
                </a>
            @endperm
                <div class="navbar-item">
                    <div class="buttons">
                        @auth
                            <button class="button is-light" onclick="document.getElementById('logout').submit()">
                                Logout
                            </button>
                            <form style="display: none" id="logout" method="POST" action="{{ route('logout') }}">@csrf</form>
                        @else
                            <a class="button is-light" href="{{ route('login') }}">
                                Log in
                            </a>
                        @endauth
                    </div>
                </div>
            </div>
        </div>
    </nav>
    @include('components.alertbanner')
    @yield('pub_body')
@endsection

resources/views/templates/public.blade.php
@extends('templates.app')

@section('body')
    <nav class="navbar is-dark" role="navigation" aria-label="main navigation">
        <div class="navbar-brand">
            <a class="navbar-item" href="{{ route('home') }}">
                LithiumATC
            </a>

            <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbar">
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
            </a>
        </div>

        <div id="navbar" class="navbar-menu">
            <div class="navbar-start">
                <a class="navbar-item" href="{{ route('home') }}">
                    Home
                </a>

                <a href="{{ route('pricing') }}" class="navbar-item">
                    Pricing
                </a>
            </div>

            <div class="navbar-end">
                @if(Auth::check() && \Illuminate\Support\Facades\Auth::user()->admin)
                    <a class="navbar-item" href="{{ route('admin.index') }}">
                        Administration
                    </a>
                @endif
                <div class="navbar-item">
                    <div class="buttons">
                        @auth
                            <button class="button is-light" onclick="document.getElementById('logout').submit()">
                                Logout
                            </button>
                            <form style="display: none" id="logout" method="POST" action="{{ route('logout') }}">@csrf</form>
                        @else
                            <a class="button is-light" href="{{ route('login') }}">
                                Log in
                            </a>
                        @endauth
                    </div>
                </div>
            </div>
        </div>
    </nav>
    @include('components.alertbanner')
    @yield('pub_body')
@endsection

resources/views/templates/smth2.blade.php
@extends('templates.app')

@section('body')
    <nav class="navbar is-dark" role="navigation" aria-label="main navigation">
        <div class="navbar-brand">
            <a class="navbar-item" href="{{ route('home') }}">
                {{ community()->name }} - LithiumATC
            </a>

            <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbar">
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
            </a>
        </div>

        <div id="navbar" class="navbar-menu">
            <div class="navbar-start">
                <a class="navbar-item" href="/">
                    Home
                </a>

                @perm('admin')
                <a href="{{ coute('c.admin') }}" class="navbar-item">
                    Admin
                </a>
                @endperm
            </div>
        </div>
    </nav>
    @yield('pub_body')
@endsection